version: "3.3"
services :
  app:
      image: nodeimage
      build: ./
      command: nodemon -L app.js
      ports:
          - "3000:3000"
      volumes:
          - ./:/app
      depends_on:
          - mongo
  mongo:
      image: mongo
      ports:
            - "27017:27017"
      volumes:
            - ./data:/data/db
      